# Generated by Django 2.1.5 on 2022-03-03 19:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220303_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 3, 19, 37, 0, 910825, tzinfo=utc), verbose_name='Publicacion'),
        ),
    ]
