# Generated by Django 3.2.12 on 2022-03-04 15:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220303_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 15, 20, 19, 841658, tzinfo=utc), verbose_name='Publicacion'),
        ),
    ]
