# Generated by Django 2.2 on 2022-03-04 19:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220304_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 19, 49, 14, 705243, tzinfo=utc), verbose_name='Publicacion'),
        ),
    ]
