# Generated by Django 2.2 on 2022-03-04 19:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220304_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 19, 50, 4, 830251, tzinfo=utc), verbose_name='Publicacion'),
        ),
    ]
