# Generated by Django 2.2 on 2022-03-04 20:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20220304_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 20, 6, 15, 676835, tzinfo=utc), verbose_name='Publicacion'),
        ),
    ]
